version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites:/sites

    # ports:
    #   - "8085:80"
    # environment:
      # - NGINX_HOST=foobar.com
      # - NGINX_PORT=80
    network_mode: 'host'
